import React, { useState, useEffect, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import './InitiatePayout.css';

const apiUrl = process.env.REACT_APP_API_URL || 'http://localhost:5000/api';

// ─── PDF helper ────────────────────────────────────────────────────────────
const downloadPDF = (payout, member) => {
  const dateLabel = new Date().toLocaleDateString('en-ZA', { dateStyle: 'long' });
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>StokvelStokkie Payout Receipt</title>
  <link rel="stylesheet" href="/PayoutPrint.css"/>
</head>
<body>
  <header>
    <span class="brand">StokvelStokkie</span>
    <span class="meta">Payout Receipt (Pending)<br/>${dateLabel}</span>
  </header>
  <h2>Payout Details</h2>
  <table>
    <tbody>
      <tr><th>Recipient</th><td>${member?.fullName || member?.userEmail || '—'}</td></tr>
      <tr><th>Amount</th><td>R ${parseFloat(payout.amount).toFixed(2)}</td></tr>
      <tr><th>Payment Method</th><td>${payout.method === 'bank' ? 'Bank Transfer' : 'Cash'}</td></tr>
      <tr><th>Reference</th><td>${payout.reference || '—'}</td></tr>
      <tr><th>Status</th><td class="status-pending">Pending Clearance</td></tr>
      <tr><th>Initiated</th><td>${dateLabel}</td></tr>
    </tbody>
  </table>
  ${payout.notes ? `<h2>Notes</h2><p class="notes-box">${payout.notes}</p>` : ''}
  <footer>Generated by StokvelStokkie · ${dateLabel}</footer>
  <script>window.onload = () => { window.print(); }<\/script>
</body>
</html>`;
  const win = window.open('', '_blank');
  win.document.write(html);
  win.document.close();
};

// ─── Component ─────────────────────────────────────────────────────────────
export const InitiatePayout = ({ members = [], groupId, groupName }) => {
  const navigate = useNavigate();

  // ── State ──────────────────────────────────────────────────────────────
  const [schedule, setSchedule]         = useState(null);   // next scheduled member from DB
  const [scheduleLoading, setSchedLoad] = useState(true);
  const [manualMode, setManualMode]     = useState(false);  // override toggle
  const [selectedMember, setSelected]   = useState(null);
  const [activePayout, setActivePayout] = useState(null); // { type: 'suggested'|'manual' }

  // Active payouts table
  const [activePayouts, setActivePayouts] = useState([]);
  const [payoutsLoading, setPayoutsLoad]  = useState(true);

  const [form, setForm] = useState({
    amount: '', method: 'bank', reference: '', notes: '',
  });
  const [submitting, setSubmitting] = useState(false);
  const [feedback, setFeedback]     = useState(null);

  const setField = (key, val) => setForm(p => ({ ...p, [key]: val }));

  // ── Fetch next scheduled payout from schedule ──────────────
  useEffect(() => {
    const fetchSchedule = async () => {
      try {
        const token = localStorage.getItem('token');
        const res = await fetch(`${apiUrl}/payouts/${groupName}/next`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        if (res.ok) {
          const data = await res.json();
          setSchedule(data); // Stores the raw { memberEmail, memberId, expectedAmount }
        }
      } catch (err) {
        console.error("Schedule fetch failed:", err);
      } finally {
        setSchedLoad(false);
      }
    };
    if (groupName) fetchSchedule();
  }, [groupName]);

  // ── Compute the clean display name safely ────────────────────
  const displayMember = useMemo(() => {
    if (!schedule) return null;
    
    // 1. Grab the identifier. We now include memberEmail and memberId based on your logs!
    const targetIdentifier = schedule.memberEmail || schedule.userEmail || schedule.memberId || schedule.userId || schedule.member;

    // 2. Find the match using the email or ID
    const matched = members.find(m => 
      String(m.email) === String(targetIdentifier) || 
      String(m._id) === String(targetIdentifier) ||
      String(m.userEmail) === String(targetIdentifier)
    );
    
    // 3. Safely construct the full name if a match is found
    let constructedName = 'Assigned Member';
    if (matched) {
      if (matched.fullName) {
        constructedName = matched.fullName; 
      } else if (matched.name && matched.surname) {
        constructedName = `${matched.name} ${matched.surname}`; 
      }
    }

    return {
      // CRITICAL FIX: Ensure _id is never undefined. Grab it from the matched member if possible!
      _id: matched ? matched._id : targetIdentifier, 
      userEmail: matched ? (matched.email || matched.userEmail) : (schedule.memberEmail || 'N/A'),
      fullName: matched ? constructedName : (targetIdentifier || 'Assigned Member')
    };
  }, [schedule, members]);
  

  // ── Who is actually selected for the form ─────────────────────────────
  // MAKE SURE THERE IS ONLY ONE OF THESE:
  const recipient = manualMode ? selectedMember : displayMember;
  const suggestedAmount = schedule?.expectedAmount ?? '';

  // ── Pre-fill amount from schedule when switching modes ─────────────────
  useEffect(() => {
    if (!manualMode && suggestedAmount) {
      setField('amount', String(suggestedAmount));
    }
  }, [manualMode, suggestedAmount]);

  // ── Fetch active (pending) payouts ─────────────────────────────────────
  useEffect(() => {
    const fetchActive = async () => {
      try {
        const token = localStorage.getItem('token');
        const res = await fetch(`${apiUrl}/payouts/${groupName}/pending`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        if (res.ok) {
          const data = await res.json();
          if (Array.isArray(data)) setActivePayouts(data);
        }
      } catch {
        // fail silently
      } finally {
        setPayoutsLoad(false);
      }
    };
    if (groupName) fetchActive();
  }, [groupName]);

  // ── Submit: initiate payout (status starts as 'pending') ───────────────
  const handleSubmit = async (e) => {
    e.preventDefault();
    setFeedback(null);
    if (!recipient) {
      setFeedback({ type: 'error', message: 'Please select a recipient.' });
      return;
    }
    if (!form.amount || parseFloat(form.amount) <= 0) {
      setFeedback({ type: 'error', message: 'Please enter a valid payout amount.' });
      return;
    }

    setSubmitting(true);
    try {
      const token = localStorage.getItem('token');
      const res = await fetch(`${apiUrl}/payouts/initiate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({
          groupName: groupName,
          memberId:       recipient._id, 
          userId:         recipient._id, // ✅ ADDED: Fixes the "userId is required" error
          payoutDate:     new Date().toISOString(), // ✅ ADDED: Fixes the "payoutDate is required" error
          recipientEmail: recipient.userEmail,
          amount:         parseFloat(form.amount),
          method:         form.method,
          reference:      form.reference,
          notes:          form.notes,
          status:         'pending',
        }),
      });
      if (!res.ok) throw new Error();

      const newPayout = await res.json();

      // Optimistically add to the active payouts table
      setActivePayouts(prev => [
        { ...newPayout, memberName: recipient.fullName || recipient.userEmail },
        ...prev,
      ]);

      setFeedback({ type: 'success', message: `Payout of R${parseFloat(form.amount).toFixed(2)} initiated for ${recipient.fullName || recipient.userEmail}. Status: Pending.` });
      setForm({ amount: '', method: 'bank', reference: '', notes: '' });
      setManualMode(false);
      setSelected(null);

    } catch {
      setFeedback({ type: 'error', message: 'Could not initiate payout. Please try again.' });
    } finally {
      setSubmitting(false);
    }
  };

  // ── Update payout status (Paid / Failed) ───────────────────────────────
  const updatePayoutStatus = async (payoutId, status) => {
    try {
      const token = localStorage.getItem('token');
      const res = await fetch(`${apiUrl}/payouts/${payoutId}/status`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({ status }),
      });
      if (!res.ok) throw new Error();
      setActivePayouts(prev =>
        prev.map(p => p._id === payoutId ? { ...p, status } : p)
      );
    } catch {
      setFeedback({ type: 'error', message: `Could not mark payout as ${status}.` });
    }
  };

  console.log("1. Members Array:", members);
  console.log("2. Schedule Data:", schedule);
  console.log("3. Display Member:", displayMember);

  // ── Render ─────────────────────────────────────────────────────────────
  return (
    <main className="po-page">
      <span aria-hidden="true" className="po-blob1" />
      <span aria-hidden="true" className="po-blob2" />

      {/* Top nav */}
      <nav className="po-topbar" aria-label="Page navigation">
        <button className="po-back-btn" onClick={() => navigate(`/treasurer-dashboard/${groupId}`)}>
          <svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
            <path d="M9 2L4 7l5 5" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
          Back to Dashboard
        </button>
        <span className="po-page-label">Treasurer · Payout Management</span>
      </nav>

      {/* ── Smart suggestion card ──────────────────────────────────── */}
      <article className="po-card po-card--suggestion" aria-label="Next scheduled payout">
        <header className="po-card-header">
          <section className="po-card-title-row">
            <span className="po-badge-label">Next Scheduled Payout</span>
            {!manualMode && (
              <button
                type="button"
                className="po-override-btn"
                onClick={() => { setManualMode(true); setFeedback(null); }}
              >
                Change Member Manually
              </button>
            )}
            {manualMode && (
              <button
                type="button"
                className="po-override-btn po-override-btn--cancel"
                onClick={() => { setManualMode(false); setSelected(null); setFeedback(null); }}
              >
                ← Use Suggested
              </button>
            )}
          </section>
        </header>

        {/* Suggested member info */}
        {!manualMode && (
            <section className="po-suggestion-body" aria-label="Suggested recipient">
                {scheduleLoading ? (
                <p className="po-loading">Loading schedule…</p>
                ) : schedule && displayMember ? (
                <figure className="po-suggestion-info">
                    <span className="po-avatar po-avatar--lg" aria-hidden="true">
                    {(displayMember.fullName || '?')[0].toUpperCase()}
                    </span>
                    <figcaption className="po-suggestion-details">
                    <p className="po-suggestion-name">{displayMember.fullName}</p>
                    <p className="po-suggestion-email">{displayMember.userEmail}</p>
                    <p className="po-suggestion-amount">
                        Expected: <strong>R {parseFloat(schedule.expectedAmount).toFixed(2)}</strong>
                    </p>
                    </figcaption>
                    <span className="po-verified-badge" aria-label="Schedule verified">
                    <svg width="12" height="12" viewBox="0 0 12 12" fill="none" aria-hidden="true">
                        <path d="M2 6l3 3 5-5" stroke="#1A7A4A" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/>
                    </svg>
                    Schedule Verified
                    </span>
                </figure>
                ) : (
                <p className="po-no-schedule">
                    No schedule found. Use "Change Member Manually" to select a recipient.
                </p>
                )}
            </section>
        )}

        {/* Manual override: member dropdown */}
        {manualMode && (
        <fieldset className="po-manual-section" aria-label="Manual member selection">
          <legend className="po-sr-only">Select a member manually</legend>
            <label className="po-field">
              <span className="po-label">Select Member <abbr title="required">*</abbr></span>
              <select
                className="po-input po-select"
                value={selectedMember?._id || ''}
                onChange={(e) => {
                  const m = members.find(m => m._id === e.target.value);
                  setSelected(m || null);
                }}
                aria-label="Select recipient member"
              >
                <option value="">— Choose a member —</option>
                {members.map((m) => (
                  <option key={m._id} value={m._id}>
                    {m.fullName || m.userEmail}
                  </option>
                ))}
              </select>
            </label>
          </fieldset>
        )}
      </article>

      {/* ── Payout form ──────────────────────────────────────────────── */}
      <article className="po-card" aria-label="Payout details form">
        <header className="po-card-header">
          <h1 className="po-card-title">Initiate Payout</h1>
          <p className="po-card-sub">
            {recipient
              ? <>Recording payout for <strong>{recipient.fullName || recipient.userEmail}</strong>.</>
              : 'Complete the details below to initiate a payout.'}
          </p>
        </header>

        {/* Feedback */}
        {feedback && (
          <p
            className={`po-alert ${feedback.type === 'error' ? 'po-alert--error' : 'po-alert--success'}`}
            role={feedback.type === 'error' ? 'alert' : 'status'}
            aria-live="assertive"
          >
            {feedback.type === 'error' ? '⚠ ' : '✓ '}{feedback.message}
          </p>
        )}

        <form className="po-form" onSubmit={handleSubmit} noValidate>

          {/* Amount */}
          <section className="po-section" aria-labelledby="po-amount-heading">
            <h2 className="po-section-title" id="po-amount-heading">Payment Info</h2>
            <label className="po-field">
              <span className="po-label">Amount (R) <abbr title="required">*</abbr></span>
              <input
                type="number"
                className="po-input"
                placeholder="0.00"
                min="0.01"
                step="0.01"
                value={form.amount}
                onChange={(e) => setField('amount', e.target.value)}
                required
                aria-label="Payout amount in Rands"
              />
              {!manualMode && suggestedAmount && (
                <span className="po-input-hint">
                  Suggested from schedule: R {parseFloat(suggestedAmount).toFixed(2)}
                </span>
              )}
            </label>
          </section>

          {/* Payment method */}
          <section className="po-section" aria-labelledby="po-method-heading">
            <h2 className="po-section-title" id="po-method-heading">Payment Method</h2>
            <fieldset className="po-method-group">
              <legend className="po-sr-only">Select payment method</legend>
              <label className={`po-method-card ${form.method === 'bank' ? 'po-method-card--active' : ''}`}>
                <input
                  type="radio" name="method" value="bank"
                  checked={form.method === 'bank'}
                  onChange={() => setField('method', 'bank')}
                  className="po-sr-only"
                />
                <svg width="22" height="22" viewBox="0 0 22 22" fill="none" aria-hidden="true">
                  <rect x="2" y="6" width="18" height="13" rx="2" stroke="currentColor" strokeWidth="1.6"/>
                  <path d="M2 10h18" stroke="currentColor" strokeWidth="1.6"/>
                  <rect x="5" y="13" width="4" height="2" rx="0.5" fill="currentColor"/>
                </svg>
                Bank Transfer
              </label>
              <label className={`po-method-card ${form.method === 'cash' ? 'po-method-card--active' : ''}`}>
                <input
                  type="radio" name="method" value="cash"
                  checked={form.method === 'cash'}
                  onChange={() => setField('method', 'cash')}
                  className="po-sr-only"
                />
                <svg width="22" height="22" viewBox="0 0 22 22" fill="none" aria-hidden="true">
                  <rect x="2" y="5" width="18" height="12" rx="2" stroke="currentColor" strokeWidth="1.6"/>
                  <circle cx="11" cy="11" r="3" stroke="currentColor" strokeWidth="1.6"/>
                  <path d="M5 8v6M17 8v6" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round"/>
                </svg>
                Cash
              </label>
            </fieldset>

            {form.method === 'bank' && (
              <label className="po-field">
                <span className="po-label">Reference / Proof of Payment</span>
                <input
                  type="text"
                  className="po-input"
                  placeholder="e.g. EFT ref #123456"
                  value={form.reference}
                  onChange={(e) => setField('reference', e.target.value)}
                />
              </label>
            )}
          </section>

          {/* Notes */}
          <section className="po-section" aria-labelledby="po-notes-heading">
            <h2 className="po-section-title" id="po-notes-heading">Notes</h2>
            <label className="po-field">
              <span className="po-label" style={{ display: 'none' }}>Notes</span>
              <textarea
                className="po-textarea"
                placeholder="Any additional context about this payout…"
                value={form.notes}
                onChange={(e) => setField('notes', e.target.value)}
                aria-label="Additional notes"
              />
            </label>
          </section>

          {/* Footer actions */}
          <footer className="po-form-footer">
            <button
              type="button"
              className="po-btn-secondary"
              onClick={() => recipient && form.amount && downloadPDF(form, recipient)}
              disabled={submitting || !recipient || !form.amount}
            >
              <svg width="15" height="15" viewBox="0 0 15 15" fill="none" aria-hidden="true">
                <path d="M7.5 1v9M4 7l3.5 3.5L11 7M2 13h11" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
              Download PDF
            </button>
            <button type="submit" className="po-btn-primary" disabled={submitting || !recipient}>
              {submitting ? (
                <><span className="po-spinner" aria-hidden="true"/>Recording…</>
              ) : (
                <>
                  <svg width="15" height="15" viewBox="0 0 15 15" fill="none" aria-hidden="true">
                    <path d="M2 8l4 4 7-7" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  Approve & Disburse
                </>
              )}
            </button>
          </footer>
        </form>
      </article>

      {/* ── Active payouts table ──────────────────────────────────────── */}
      <article className="po-card po-card--table" aria-label="Active pending payouts">
        <header className="po-card-header">
          <h2 className="po-card-title po-card-title--sm">Active Payouts</h2>
          <p className="po-card-sub">Update payout status once cleared or if a transfer fails.</p>
        </header>

        {payoutsLoading ? (
          <p className="po-loading">Loading payouts…</p>
        ) : activePayouts.length === 0 ? (
          <p className="po-empty">No active payouts. Initiated payouts will appear here.</p>
        ) : (
          <section className="po-table-wrap" aria-label="Payouts table">
            <table className="po-table">
              <thead>
                <tr>
                  <th scope="col">Member</th>
                  <th scope="col">Amount</th>
                  <th scope="col">Method</th>
                  <th scope="col">Status</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                {activePayouts.map((p) => (
                  <tr key={p._id}>
                    <td>{p.memberName || p.recipientEmail}</td>
                    <td>R {parseFloat(p.amount).toFixed(2)}</td>
                    <td>{p.method === 'bank' ? 'Bank Transfer' : 'Cash'}</td>
                    <td>
                      <span className={`po-status-pill po-status-pill--${p.status}`}>
                        {p.status.charAt(0).toUpperCase() + p.status.slice(1)}
                      </span>
                    </td>
                    <td>
                      {p.status === 'pending' && (
                        <menu className="po-action-btns">
                          <li>
                            <button
                              className="po-action-btn po-action-btn--paid"
                              onClick={() => updatePayoutStatus(p._id, 'paid')}
                              type="button"
                            >
                              Mark as Paid
                            </button>
                          </li>
                          <li>
                            <button
                              className="po-action-btn po-action-btn--failed"
                              onClick={() => updatePayoutStatus(p._id, 'failed')}
                              type="button"
                            >
                              Mark as Failed
                            </button>
                          </li>
                        </menu>
                      )}
                      {p.status !== 'pending' && (
                        <span className="po-action-resolved">—</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        )}
      </article>

    </main>
  );
};