import React, { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import './RecordMinutes.css';

// ─── Helpers ───────────────────────────────────────────────────────────────
const uid         = () => Date.now() + Math.random();
const emptyContrib  = () => ({ id: uid(), member: '', amount: '', status: 'paid' });
const emptyDecision = () => ({ id: uid(), text: '' });

const defaultForm = () => ({
  meetingDate:   '',
  meetingTime:   '',
  contributions: [emptyContrib()],
  decisions:     [emptyDecision()],
  notes:         '',
});

// ─── PDF helper ────────────────────────────────────────────────────────────
// Opens a print-ready window — no extra packages needed.
const downloadPDF = (form) => {
  const dateLabel = form.meetingDate
    ? new Date(form.meetingDate).toLocaleDateString('en-ZA', { dateStyle: 'long' })
    : '—';
  const timeLabel = form.meetingTime || '—';

  const contribRows = form.contributions
    .filter((c) => c.member.trim())
    .map(
      (c) => `
        <tr>
          <td>${c.member}</td>
          <td>R ${parseFloat(c.amount || 0).toFixed(2)}</td>
          <td class="status-${c.status}">${c.status.charAt(0).toUpperCase() + c.status.slice(1)}</td>
        </tr>`
    )
    .join('');

  const decisionItems = form.decisions
    .filter((d) => d.text.trim())
    .map((d, i) => `<li>${i + 1}. ${d.text}</li>`)
    .join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>StokvelStokkie Meeting Minutes – ${dateLabel}</title>
  <link rel="stylesheet" href="/MinutesPrint.css"/>
</head>
<body>
  <header>
    <span class="brand">StokvelStokkie</span>
    <span class="meta">
      Meeting Minutes<br/>
      ${dateLabel} at ${timeLabel}
    </span>
  </header>
 
  <h2>Contributions Collected</h2>
  <table>
    <thead><tr><th>Member</th><th>Amount</th><th>Status</th></tr></thead>
    <tbody>${contribRows || '<tr><td colspan="3">No contributions recorded.</td></tr>'}</tbody>
  </table>
 
  <h2>Decisions Made</h2>
  <ol>${decisionItems || '<li>No decisions recorded.</li>'}</ol>
 
  <h2>General Notes</h2>
  <p class="notes-box">${form.notes.trim() || 'No notes recorded.'}</p>
 
  <footer>Generated by StokvelStokkie · ${new Date().toLocaleDateString('en-ZA')}</footer>
 
  <script>window.onload = () => { window.print(); }<\/script>
</body>
</html>`;

  const win = window.open('', '_blank');
  win.document.write(html);
  win.document.close();
};

// ─── Component ────────────────────────────────────────────────────────────
export const RecordMinutes = () => {
  const navigate = useNavigate();
  const { groupId } = useParams();

  const [form, setForm]             = useState(defaultForm());
  const [submitting, setSubmitting] = useState(false);
  const [feedback, setFeedback]     = useState(null); // { type: 'error'|'success', message }

  // ── Generic field setter ───────────────────────────────────────────────
  const setField = (key, value) => setForm((prev) => ({ ...prev, [key]: value }));

  // ── Contributions ──────────────────────────────────────────────────────
  const updateContrib = (id, key, value) =>
    setForm((prev) => ({
      ...prev,
      contributions: prev.contributions.map((c) => (c.id === id ? { ...c, [key]: value } : c)),
    }));
  const addContrib    = () => setForm((prev) => ({ ...prev, contributions: [...prev.contributions, emptyContrib()] }));
  const removeContrib = (id) => setForm((prev) => ({ ...prev, contributions: prev.contributions.filter((c) => c.id !== id) }));

  // ── Decisions ──────────────────────────────────────────────────────────
  const updateDecision = (id, value) =>
    setForm((prev) => ({
      ...prev,
      decisions: prev.decisions.map((d) => (d.id === id ? { ...d, text: value } : d)),
    }));
  const addDecision    = () => setForm((prev) => ({ ...prev, decisions: [...prev.decisions, emptyDecision()] }));
  const removeDecision = (id) => setForm((prev) => ({ ...prev, decisions: prev.decisions.filter((d) => d.id !== id) }));

  // ── Validation ─────────────────────────────────────────────────────────
  const validate = () => {
    if (!form.meetingDate || !form.meetingTime) {
      setFeedback({ type: 'error', message: 'Please fill in the meeting date and time.' });
      return false;
    }
    return true;
  };

  // ── Clean payload (strip blank rows) ──────────────────────────────────
  const buildPayload = () => ({
    meetingDate:   form.meetingDate,
    meetingTime:   form.meetingTime,
    contributions: form.contributions.filter((c) => c.member.trim()),
    decisions:     form.decisions.filter((d) => d.text.trim()).map((d) => d.text.trim()),
    notes:         form.notes.trim(),
  });

  // ── Submit: POST to backend ────────────────────────────────────────────
  const handleSubmit = async (e) => {
    e.preventDefault();
    setFeedback(null);
    if (!validate()) return;

    setSubmitting(true);
    try {
      // Grab the URL from the .env file
      const apiUrl = process.env.REACT_APP_API_URL || 'http://localhost:5000'; // Fallback to localhost if env variable is missing

      const res = await fetch(`${apiUrl}/api/minutes/${groupId}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(buildPayload()),
      });
      if (!res.ok) throw new Error('Server error');
      setFeedback({ type: 'success', message: 'Minutes saved to the database successfully!' });
      setForm(defaultForm());
    } catch {
      setFeedback({ type: 'error', message: 'Could not save minutes. Please try again.' });
    } finally {
      setSubmitting(false);
    }
  };

  // ── Download PDF ───────────────────────────────────────────────────────
  const handleDownloadPDF = () => {
    setFeedback(null);
    if (!validate()) return;
    downloadPDF(form);
  };

  // ── Reset ──────────────────────────────────────────────────────────────
  const handleReset = () => { setForm(defaultForm()); setFeedback(null); };

  // ── Render ─────────────────────────────────────────────────────────────
  return (
    <main className="rm-page">
      <span aria-hidden="true" className="rm-blob1" />
      <span aria-hidden="true" className="rm-blob2" />

      {/* Top nav */}
      <nav className="rm-topbar" aria-label="Page navigation">
        <button className="rm-back-btn" onClick={() => navigate(`/admin-dashboard/${groupId}`)}>
          <svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
            <path d="M9 2L4 7l5 5" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
          Back
        </button>
        <span className="rm-page-label">Admin · Record Minutes</span>
      </nav>

      {/* Card */}
      <article className="rm-card">

        <header className="rm-card-header">
          <h1 className="rm-card-title">Record Meeting Minutes</h1>
          <p className="rm-card-sub">
            Fill in the details below, then save to the database and/or download a PDF copy.
          </p>
        </header>

        {/* Feedback banner */}
        {feedback && (
          <p
            className={`rm-alert ${feedback.type === 'error' ? 'rm-alert-error' : 'rm-alert-success'}`}
            role={feedback.type === 'error' ? 'alert' : 'status'}
            aria-live="assertive"
          >
            {feedback.type === 'error' ? '⚠ ' : '✓ '}
            {feedback.message}
          </p>
        )}

        <form className="rm-form" onSubmit={handleSubmit} noValidate>

          {/* ── 1. Date & time ──────────────────────────────────────── */}
          <section className="rm-section" aria-labelledby="section-details">
            <h2 className="rm-section-title" id="section-details">Meeting Details</h2>
            <div className="rm-row">
              <label className="rm-field">
                <span className="rm-label">Date <abbr title="required">*</abbr></span>
                <input
                  type="date"
                  className="rm-input"
                  value={form.meetingDate}
                  onChange={(e) => setField('meetingDate', e.target.value)}
                  required
                />
              </label>
              <label className="rm-field">
                <span className="rm-label">Time <abbr title="required">*</abbr></span>
                <input
                  type="time"
                  className="rm-input"
                  value={form.meetingTime}
                  onChange={(e) => setField('meetingTime', e.target.value)}
                  required
                />
              </label>
            </div>
          </section>

          {/* ── 2. Contributions ────────────────────────────────────── */}
          <section className="rm-section" aria-labelledby="section-contributions">
            <h2 className="rm-section-title" id="section-contributions">Contributions Collected</h2>
            <table className="rm-contrib-table" aria-label="Contributions table">
              <thead>
                <tr>
                  <th scope="col">Member</th>
                  <th scope="col">Amount (R)</th>
                  <th scope="col">Status</th>
                  <th scope="col"><span aria-hidden="true">⋯</span></th>
                </tr>
              </thead>
              <tbody>
                {form.contributions.map((c, idx) => (
                  <tr key={c.id}>
                    <td>
                      <input
                        type="text"
                        className="rm-input"
                        placeholder="Full name"
                        value={c.member}
                        onChange={(e) => updateContrib(c.id, 'member', e.target.value)}
                        aria-label={`Member name row ${idx + 1}`}
                      />
                    </td>
                    <td>
                      <input
                        type="number"
                        className="rm-input"
                        placeholder="0.00"
                        min="0"
                        step="0.01"
                        value={c.amount}
                        onChange={(e) => updateContrib(c.id, 'amount', e.target.value)}
                        aria-label={`Amount row ${idx + 1}`}
                      />
                    </td>
                    <td>
                      <select
                        className={`rm-input rm-select rm-status-select rm-status-${c.status}`}
                        value={c.status}
                        onChange={(e) => updateContrib(c.id, 'status', e.target.value)}
                        aria-label={`Payment status row ${idx + 1}`}
                      >
                        <option value="paid">Paid</option>
                        <option value="unpaid">Unpaid</option>
                        <option value="partial">Partial</option>
                      </select>
                    </td>
                    <td>
                      {form.contributions.length > 1 && (
                        <button
                          type="button"
                          className="rm-remove-btn"
                          onClick={() => removeContrib(c.id)}
                          aria-label={`Remove contribution row ${idx + 1}`}
                        >×</button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            <button type="button" className="rm-add-btn" onClick={addContrib}>
              + Add row
            </button>
          </section>

          {/* ── 3. Decisions ────────────────────────────────────────── */}
          <section className="rm-section" aria-labelledby="section-decisions">
            <h2 className="rm-section-title" id="section-decisions">Decisions Made</h2>
            <ol className="rm-decision-list" aria-label="Decisions list">
              {form.decisions.map((d, idx) => (
                <li key={d.id} className="rm-decision-item">
                  <label className="rm-field" style={{ flex: 1 }}>
                    <span className="rm-label" style={{ display: 'none' }}>Decision {idx + 1}</span>
                    <input
                      type="text"
                      className="rm-input"
                      placeholder={`Decision ${idx + 1}`}
                      value={d.text}
                      onChange={(e) => updateDecision(d.id, e.target.value)}
                      aria-label={`Decision ${idx + 1}`}
                    />
                  </label>
                  {form.decisions.length > 1 && (
                    <button
                      type="button"
                      className="rm-remove-btn"
                      onClick={() => removeDecision(d.id)}
                      aria-label={`Remove decision ${idx + 1}`}
                    >×</button>
                  )}
                </li>
              ))}
            </ol>
            <button type="button" className="rm-add-btn" onClick={addDecision}>
              + Add decision
            </button>
          </section>

          {/* ── 4. Notes ────────────────────────────────────────────── */}
          <section className="rm-section" aria-labelledby="section-notes">
            <h2 className="rm-section-title" id="section-notes">General Notes</h2>
            <label className="rm-field">
              <span className="rm-label" style={{ display: 'none' }}>Notes</span>
              <textarea
                className="rm-textarea"
                placeholder="Any additional notes, announcements, or context from the meeting…"
                value={form.notes}
                onChange={(e) => setField('notes', e.target.value)}
                aria-label="General notes"
              />
            </label>
          </section>

          {/* ── Footer actions ───────────────────────────────────────── */}
          <footer className="rm-form-footer">
            <button type="button" className="rm-btn-ghost" onClick={handleReset} disabled={submitting}>
              Clear form
            </button>
            <button type="button" className="rm-btn-secondary" onClick={handleDownloadPDF} disabled={submitting}>
              <svg width="15" height="15" viewBox="0 0 15 15" fill="none" aria-hidden="true">
                <path d="M7.5 1v9M4 7l3.5 3.5L11 7M2 13h11" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
              Download PDF
            </button>
            <button type="submit" className="rm-btn-primary" disabled={submitting}>
              {submitting ? (
                <>
                  <span className="rm-btn-spinner" aria-hidden="true" />
                  Saving…
                </>
              ) : (
                <>
                  <svg width="15" height="15" viewBox="0 0 15 15" fill="none" aria-hidden="true">
                    <path d="M2 8l4 4 7-7" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  Save Minutes
                </>
              )}
            </button>
          </footer>

        </form>
      </article>
    </main>
  );
};
export default RecordMinutes;
