# --- CODACY UPLOAD ---
    - name: Upload Coverage to Codacy
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: backend/coverage/lcov.info,frontend/coverage/lcov.info