# --- CODACY UPLOAD (STEP 2) ---
    - name: Run Codacy Coverage Reporter
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r backend/coverage/lcov.info -r frontend/coverage/lcov.info